
server:
  port: 8081
spring:
  cloud:
    config:
      uri: http://localhost:8888
      name:
      enabled: false
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/eum_user?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect # ??? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # ?? ?? ??
    generate-ddl: true
#eureka:
#  #  instance:
#  #    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
kakao :
  client-id: 1a354a3d4dc989747906944c3c188196
  redirect-url: http://localhost:8081/auth-service/api/v2/auth
  admin-key: ${admin-key}