name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # 1. java 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: actions/checkout@v4
    - run: touch ./src/main/resources/application.yml
    - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
    - run: cat ./src/main/resources/application.yml
    # 2. spring boot 애플리케이션 빌드
    - name: build with Gradle
      uses: gradle/gradle-build-action@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
        arguments:  ./gradlew build -x test
    # - name: Build with Gradle Wrapper
    #   run: ./gradlew build
 # # 3. Docker 이미지 빌드
 #    - name: docker image build
 #      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo .

 #    # 4. DockerHub 로그인
 #    - name: docker login
 #      uses: docker/login-action@v2
 #      with:
 #        username: ${{ secrets.DOCKERHUB_USERNAME }}
 #        password: ${{ secrets.DOCKERHUB_PASSWORD }}

 #    # 5. Docker Hub 이미지 푸시
 #    - name: docker Hub push
 #      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo
